# Generated by Django 3.1.2 on 2021-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0003_alter_cake_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
